config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :estados
  get 'liberar', to: 'estados#liberar'
  get 'liberaH', to: 'estados#liberaH'
  get 'buscarReservacion', to: 'reservas#buscar'
  get 'mostrar', to: 'reservas#muestra'
  get 'listarH_todas', to: 'estados#muestra'
  get 'mostrarDisp', to: 'estados#mostrarDisp'
  get 'mostrarReservas', to: 'reservas#listar'
  get 'fotos', to: 'estados#fotos'

  root :to => 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/habitacion.rb
class Habitacion 
	attr_accessor :id, :value
end

app/models/reserva.rb
class Reserva < ApplicationRecord
  belongs_to :estado
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  def liberar
  end

  def muestra
    @estados = Estado.order(:id)
  end

  def mostrarDisp
    @estados = Estado.where(estado: 0).order(:id)
  end

  def liberaH
    x = params[:nH]
    stateRoom = Estado.find_by(id: x)
    begin
      value = stateRoom.estado == 0 ? 1 : 0
      if value == 0
        stateRoom.update(estado: value)

        reserva = Reserva.find_by(estado_id: x)
        reserva.destroy

        respond_to do |format|
          format.html { redirect_to stateRoom, notice: 'Liberar reservacion, accion realizada con exito' }
          format.json { render :show, status: :created, location: stateRoom }
        end
      else
        respond_to do |format|
          format.html { redirect_to stateRoom, notice: 'Liberar reservacion, la habitacion esta disponible no hace falta liberar' }
          format.json { render :show, status: :created, location: stateRoom }
        end
      end
    rescue
      render "liberar"
    end  
  end

  def fotos
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:estado, :tipoHabitacion, :precioNoche, :personasHabitacion)
    end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  def index
    @reservas = Reserva.all
  end

  def listar
    @reservas = Reserva.select(:nombreCliente, :estado_id).order(:nombreCliente)
  end

  def show
  end

  def new
    @reserva = Reserva.new
  end

  def

  def edit
  end

  def create
    @reserva = Reserva.new(reserva_params)

    stateRoom = Estado.find_by(id: @reserva.estado_id)
    begin
      if(stateRoom.estado == 0)
        stateRoom.update(estado: 1)

        respond_to do |format|
          if @reserva.save
            format.html { redirect_to @reserva, notice: 'Reservacion realizada con exito' }
            format.json { render :show, status: :created, location: @reserva }
          else
            format.html { redirect_to stateRoom, notice: 'Reservacion no registrada, validar campos' }
            format.json { render :show, status: :created, location: stateRoom }
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to stateRoom, notice: 'Habitacion ocupada, Reservacion no registrada' }
          format.json { render :show, status: :created, location: stateRoom }
        end
      end
    rescue
      render 'new'
    end
  end

  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reservacion eliminada' }
      format.json { head :no_content }
    end
  end

  private
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    def reserva_params
      params.require(:reserva).permit(:estado_id, :nombreCliente, :cedulaCliente, :celular, :correo, :numeroDias, :totalPagar)
    end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/estados/_form.html.erb
<%= form_with(model: estado, local: true) do |form| %>

  <div class="field">
    <%= form.label :estado %>
    <%= form.number_field :estado %>
  </div>

  <div class="field">
    <%= form.label :tipoHabitacion %>
    <%= form.text_field :tipoHabitacion %>
  </div>

  <div class="field">
    <%= form.label :precioNoche %>
    <%= form.text_field :precioNoche %>
  </div>

  <div class="field">
    <%= form.label :personasHabitacion %>
    <%= form.number_field :personasHabitacion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estados/_state.html.erb
<div style="width: 80%; margin: 20px;" class="m-auto">
  <h1 style="text-align: center">Liberar Reservacion</h1>
  <%= form_with(model: estado, local: true) do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
        <% estado.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <label for="estado_estado">Numero Habitacion</label>

      <%= form.text_field :estado, :placeholder=> "Ej: 3", :title=> "Numero Habitacion", :pattern=> "[1-9](\d{1})?", :class=> "form-control", :value=> "0"%>
    </div>

  </div>
  <div class="actions">
      <button type="submit" class="btn btn-primary" name="commit" value="Update Estado" data-disable-with="Update Estado" >Submit</button>
    </div>
<% end %>
</div>

app/views/estados/edit.html.erb
<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/fotos.html.erb
<%= stylesheet_link_tag 'estados', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'welcome/navbar'%>

<div id="Uni" class="d1">
    <div ><h2>Habitación Unipersonal</h2></div>
    <div id="ImagUni"></div>
</div>

<div id="Uni" class="d2">
    <div><h2>Habitación Doble</h2></div>
    <div id="ImagDob"></div>
</div>

<div id="Uni" class="d3">
    <div><h2>Habitación Familiar</h2></div>
    <div id="ImagFam"></div>
</div>

<div id="Uni" class="d4">
    <div><h2>Habitación Suite</h2></div>
    <div id="ImagSui"></div>
</div>

app/views/estados/index.html.erb
<%= render 'welcome/navbar' %> 

<p id="notice"><%= notice %></p>

<h1>Estados</h1>
<table>
  <thead>
    <tr>
      <th>Habitacion</th>
      <th>Estado</th>
      <th>Tipohabitacion</th>
      <th>Precionoche</th>
      <th>Personashabitacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.id %></td>
        <td><%= estado.estado %></td>
        <td><%= estado.tipoHabitacion %></td>
        <td><%= estado.precioNoche %></td>
        <td><%= estado.personasHabitacion %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/liberar.html.erb
<%= render 'welcome/navbar' %>
<div style="width: 80%; margin: 20px;" class="m-auto">
	<h1 style="text-align: center">Liberar Reservacion</h1>

	<form class="needs-validation" novalidate action="/liberaH" method="get " accept-charset="UTF-8">
		
		<div class="form-group">
	    	<label for="nH">Numero Habitacion</label>
	    	<input type="text" class="form-control" id="nH" placeholder="Ej: 3" title="Numero Habitacion" pattern="[1-9](\d{1})?" required name="nH">
    	</div>
    	<button type="submit" class="btn btn-primary">Submit</button>
    </form>


	<script>
		// Example starter JavaScript for disabling form submissions if there are invalid fields
		(function() {
		  'use strict';
		  window.addEventListener('load', function() {
		    // Fetch all the forms we want to apply custom Bootstrap validation styles to
		    var forms = document.getElementsByClassName('needs-validation');
		    // Loop over them and prevent submission
		    var validation = Array.prototype.filter.call(forms, function(form) {
		      form.addEventListener('submit', function(event) {
		        if (form.checkValidity() === false) {
		          event.preventDefault();
		          event.stopPropagation();
		        }
		        form.classList.add('was-validated');
		      }, false);
		    });
		  }, false);
		})();
	</script>

</div>

app/views/estados/mostrarDisp.html.erb
<%= render 'welcome/navbar'%>

<div style="margin: 20px;">
    <div class="row">
      <div class="col-md-10">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">N° Habitacion</th>
              <th scope="col">Tipo Habitacion</th>
              <th scope="col">Precio x Dia</th>
              <th scope="col">Capacidad</th>
              <th scope="col">Estado</th>
            </tr>
          </thead>
          <tbody>
            <% @estados.each do |estado| %>
              <tr>
                <th scope="row"><%= estado.id %></th>
                <td><%= estado.tipoHabitacion %></td>
                <td>$ <%= estado.precioNoche %></td>
                <td><%= estado.personasHabitacion %></td>

                <%if estado.estado == 0%>
                  <td>Disponible</td>  
                <%else%>
                  <td>Ocupada</td>  
                <%end%>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-md-2">
        <a href="/liberar" class="btn btn-primary">Liberar</a>
        <a href="/reservas/new" class="btn btn-primary">Reservar</a>
      </div>
    </div>
</div>

app/views/estados/muestra.html.erb
<%= render 'welcome/navbar'%>

<div style="margin: 20px;">
    <div class="row">
      <div class="col-md-10">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">N° Habitacion</th>
              <th scope="col">Tipo Habitacion</th>
              <th scope="col">Precio x Dia</th>
              <th scope="col">Capacidad</th>
              <th scope="col">Estado</th>
            </tr>
          </thead>
          <tbody>
            <% @estados.each do |estado| %>
              <tr>
                <th scope="row"><%= estado.id %></th>
                <td><%= estado.tipoHabitacion %></td>
                <td>$ <%= estado.precioNoche %></td>
                <td><%= estado.personasHabitacion %></td>

                <%if estado.estado == 0%>
                  <td>Disponible</td>  
                <%else%>
                  <td>Ocupada</td>  
                <%end%>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-md-2">
        <a href="/liberar" class="btn btn-primary">Liberar</a>
        <a href="/reservas/new" class="btn btn-primary">Reservar</a>
      </div>
    </div>
</div>

app/views/estados/new.html.erb
<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<%= render 'welcome/navbar' %> 

<div class="alert alert-success">
  <strong><%= notice %>!</strong>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  </head>
  <body>
      <%= yield :header %>
      <%= yield %>
  </body>
</html>

app/views/reservas/_form.html.erb
<%= render 'welcome/navbar' %> 
<div style="width: 80%; margin: 20px" class="m-auto">
    <h1 style="text-align: center">Reservacion</h1>
    <br>

    <form class="needs-validation" novalidate action="/reservas" accept-charset="UTF-8" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

        <div class="form-group field">
          <label for="reserva_nombreCliente">Nombre</label>
          <input type="text" class="form-control" id="reserva_nombreCliente" placeholder="Ej: Rosa Vaca" title="Nombre" pattern="[a-zA-Z]{3,20}" name="reserva[nombreCliente]" required>

          <div class="invalid-feedback">Falta nombre.</div>
          <div class="valid-feedback">Parece correcto!</div>
        </div>

        <div class="form-group field">
          <label for="reserva_cedulaCliente">Cedula</label>
          <input type="text" class="form-control" id="reserva_cedulaCliente" placeholder="Ej: 001-123456-789A" pattern="\d{3}-?\d{6}-?\d{4}[a-zA-Z]{1}" title="Cedula de Identidad" required name="reserva[cedulaCliente]">
          <div class="invalid-feedback">Falta cedula.</div>
          <div class="valid-feedback">Parece correcto!</div>
        </div>

        <div class="form-group field">
          <label for="reserva_celular">Celular</label>
          <input type="text" class="form-control" id="reserva_celular" placeholder="Ej: 12345678" pattern="[8|5][0-9]{7}" title="Numero telefonico" required name="reserva[celular]">

          <div class="invalid-feedback">Falta numero telefonico.</div>
          <div class="valid-feedback">Parece correcto!</div>
        </div>

      <div class="form-group field">
          <label for="reserva_correo">Correo electronico</label>
          <input type="email" class="form-control" id="reserva_correo" placeholder="Ej: name@example.com" title="Email" name="reserva[correo]">
      </div>

      
        <div class="form-group field">
          <label for="reserva_estado_id">Numero habitacion</label>
          <input type="text" class="form-control" id="reserva_estado_id" placeholder="Ej: 3" title="Numero Habitacion" pattern="[1-9](\d{1})?" required name="reserva[estado_id]">
          <div class="invalid-feedback">
              Falta numero habitacion.
          </div>
          <div class="valid-feedback">
            Parece correcto!
          </div>
        </div>

        <div class="actions">
          <input type="submit" name="commit" value="Create Reserva" class="btn btn-primary" data-disable-with="Crear Reserva" />
      </div>
    </form>
  </div>

  <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
      'use strict';
      window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
          form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
              event.preventDefault();
              event.stopPropagation();
            }
            form.classList.add('was-validated');
          }, false);
        });
      }, false);
    })();
  </script>

app/views/reservas/edit.html.erb
<!-- <h1>Editing Reserva</h1> -->

<%= render 'form', reserva: @reserva %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th>Nombrecliente</th>
      <th>Cedulacliente</th>
      <th>Celular</th>
      <th>Correo</th>
      <th>Numerodias</th>
      <th>Totalpagar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.estado_id %></td>
        <td><%= reserva.nombreCliente %></td>
        <td><%= reserva.cedulaCliente %></td>
        <td><%= reserva.celular %></td>
        <td><%= reserva.correo %></td>
        <td><%= reserva.numeroDias %></td>
        <td><%= reserva.totalPagar %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserva', new_reserva_path %>

app/views/reservas/listar.html.erb
<%= render 'welcome/navbar'%>

<div style="margin: 20px;">
    <div class="row">
      <div class="col-md-10">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">N° Habitacion</th>
              <th scope="col">Nombre Cliente</th>
            </tr>
          </thead>
          <tbody>
            <% @reservas.each do |reservas| %>
              <tr>
                <th scope="row"><%= reservas.estado_id %></th>
                <td><%= reservas.nombreCliente %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/reservas/new.html.erb
<%= render 'form', reserva: @reserva %>

app/views/reservas/show.html.erb
<%= render 'welcome/navbar' %> 

<div class="alert alert-success">
  <strong><%= notice %>!</strong>
</div>

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <li class="nav-item active">
        <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Opciones
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/reservas/new">Reservar Habitación</a>
          <a class="dropdown-item" href="/liberar">Liberar Reservación</a>
          <a class="dropdown-item" href="/mostrarDisp">Listar Habitaciones Disponibles</a>
          <a class="dropdown-item" href="/listarH_todas">Listar Habitaciones</a>
          <a class="dropdown-item" href="/mostrarReservas">Listar Reservacines</a>
          <a class="dropdown-item" href="/fotos">Ver Fotos</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<%content_for :header do %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <li class="nav-item active">
        <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Opciones
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/reservas/new">Reservar Habitación</a>
          <a class="dropdown-item" href="/liberar">Liberar Reservación</a>
          <a class="dropdown-item" href="/mostrarDisp">Listar Habitaciones Disponibles</a>
          <a class="dropdown-item" href="/listarH_todas">Listar Habitaciones</a>
          <a class="dropdown-item" href="/mostrarReservas">Listar Reservacines</a>
          <a class="dropdown-item" href="/fotos">Ver Fotos</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<% end %>